import type { TurnInput, TurnOutput } from '../contracts.js';
import type { TextProvider } from '../providers/types.js';
import { completeWithFallback } from '../provider-runtime.js';
import type { MemoryStore, RelationshipDimensions } from './store.js';
import type { ResidentStore } from '../residents.js';

type ExtractedMemory = { key:string;kind:string;subject:string;text:string;importance:number;confidence:number;retention:'permanent'|'important'|'preference'|'routine';tags:string[];unresolved:boolean };
type Extraction = { memories:ExtractedMemory[];relationship?:Partial<RelationshipDimensions>;relationshipTag?:string;playerIntroducedName?:boolean };
type Job = { turn:TurnInput;response:string };

const kinds=new Set(['core_fact','preference','introduction','promise','boundary','grievance','gratitude','shared_event','conversation']);
const subjects=new Set(['player','npc','shared']);
const retentions=new Set(['permanent','important','preference','routine']);
const dimensions:Array<keyof RelationshipDimensions>=['familiarity','trust','warmth','respect','fear','irritation','obligation'];
function cleanKey(value:unknown){return String(value??'').toLowerCase().replace(/[^a-z0-9:_-]+/g,'-').replace(/^-|-$/g,'').slice(0,120);}
function policy(turn:TurnInput){const settings=turn.context.memory as {enabled?:boolean;retentionDays?:number;minimumImportance?:number}|undefined;return {enabled:settings?.enabled!==false,days:Number.isFinite(settings?.retentionDays)&&settings!.retentionDays!>0?Math.min(settings!.retentionDays!,3650):undefined,minimum:Number.isFinite(settings?.minimumImportance)?Math.max(0,Math.min(1,settings!.minimumImportance!)):0};}
function expiry(kind:ExtractedMemory['retention'],turn:TurnInput){const defaults={permanent:0,important:365,preference:90,routine:30}[kind];const cap=policy(turn).days;const days=cap===undefined?defaults:defaults?Math.min(defaults,cap):cap;return days?new Date(Date.now()+days*86_400_000).toISOString():undefined;}
function jsonObject(text:string){const raw=text.trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');const start=raw.indexOf('{'),end=raw.lastIndexOf('}');if(start<0||end<=start)throw new Error('memory_invalid_json');return JSON.parse(raw.slice(start,end+1));}
function validate(value:unknown):Extraction{if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('memory_invalid_shape');const v=value as any;const memories:Array<ExtractedMemory>=[];for(const item of Array.isArray(v.memories)?v.memories.slice(0,6):[]){if(!item||typeof item!=='object')continue;const key=cleanKey(item.key),kind=String(item.kind??''),subject=String(item.subject??''),text=String(item.text??'').trim().slice(0,240),retention=String(item.retention??'') as ExtractedMemory['retention'];const importance=Number(item.importance),confidence=Number(item.confidence);if(!key||!kinds.has(kind)||!subjects.has(subject)||!text||!retentions.has(retention)||!Number.isFinite(importance)||!Number.isFinite(confidence)||confidence<.6)continue;memories.push({key,kind,subject,text,retention,importance:Math.max(0,Math.min(1,importance)),confidence:Math.max(0,Math.min(1,confidence)),tags:(Array.isArray(item.tags)?item.tags:[]).map(cleanKey).filter(Boolean).slice(0,8),unresolved:item.unresolved===true});}const relationship:Partial<RelationshipDimensions>={};if(v.relationship&&typeof v.relationship==='object')for(const key of dimensions){const n=Number(v.relationship[key]);if(Number.isFinite(n))relationship[key]=Math.max(-10,Math.min(10,n));}return{memories,relationship,relationshipTag:cleanKey(v.relationshipTag)||undefined,playerIntroducedName:v.playerIntroducedName===true};}

export class MemoryExtractionQueue {
  private pending:Job[]=[];private running=0;private dropped=0;private failed=0;
  private blockedServers=new Set<string>();private runningByServer=new Map<string,number>();private serverWaiters=new Map<string,Array<()=>void>>();
  constructor(private readonly primary:TextProvider,private readonly fallback:TextProvider,private readonly store:MemoryStore,private readonly residents:ResidentStore,private readonly concurrency=4,private readonly maximum=500,
    private readonly execute?: (turn: TurnInput, work: () => Promise<TurnOutput>) => Promise<unknown>){}
  stats(){return{depth:this.pending.length,running:this.running,dropped:this.dropped,failed:this.failed};}
  enqueue(turn:TurnInput,response:string){if(!policy(turn).enabled||this.blockedServers.has(turn.serverId))return false;if(this.pending.length>=this.maximum){this.dropped++;return false;}this.pending.push({turn,response});this.drain();return true;}
  async blockServer(serverId:string){this.blockedServers.add(serverId);this.pending=this.pending.filter(job=>job.turn.serverId!==serverId);if((this.runningByServer.get(serverId)??0)===0)return;await new Promise<void>(resolve=>{const waiters=this.serverWaiters.get(serverId)??[];waiters.push(resolve);this.serverWaiters.set(serverId,waiters);});}
  unblockServer(serverId:string){this.blockedServers.delete(serverId);}
  async runMemoryWrite<T>(serverId:string,work:()=>Promise<T>):Promise<T|undefined>{if(this.blockedServers.has(serverId))return undefined;this.runningByServer.set(serverId,(this.runningByServer.get(serverId)??0)+1);try{return await work();}finally{this.finishServer(serverId);}}
  private finishServer(serverId:string){const remaining=(this.runningByServer.get(serverId)??1)-1;if(remaining>0)this.runningByServer.set(serverId,remaining);else{this.runningByServer.delete(serverId);for(const resolve of this.serverWaiters.get(serverId)??[])resolve();this.serverWaiters.delete(serverId);}}
  private drain(){while(this.running<this.concurrency&&this.pending.length){const job=this.pending.shift()!;if(this.blockedServers.has(job.turn.serverId))continue;const serverId=job.turn.serverId;this.running++;this.runningByServer.set(serverId,(this.runningByServer.get(serverId)??0)+1);void this.process(job).catch(()=>{this.failed++;}).finally(()=>{this.running--;this.finishServer(serverId);this.drain();});}}
  private async process({turn,response}:Job){if(this.blockedServers.has(turn.serverId))return;const characterId=String((turn.context.player as any)?.characterId??'unknown-character'),npcId=String(turn.npc.id??'unknown-npc');const prompt=`Extract only durable or socially meaningful memory from this exchange.\nSchema: {"memories":[{"key":"stable-topic-key","kind":"core_fact|preference|introduction|promise|boundary|grievance|gratitude|shared_event|conversation","subject":"player|npc|shared","text":"third-person fact","importance":0..1,"confidence":0..1,"retention":"permanent|important|preference|routine","tags":["keyword"],"unresolved":false}],"relationship":{"familiarity":-10..10,"trust":-10..10,"warmth":-10..10,"respect":-10..10,"fear":-10..10,"irritation":-10..10,"obligation":-10..10},"relationshipTag":"optional","playerIntroducedName":false}\nPlayer: ${turn.input.slice(0,500)}\nNPC: ${response.slice(0,1200)}`;const extractionTurn:TurnInput={serverId:turn.serverId,sessionId:turn.sessionId,requestId:turn.requestId,npc:{id:npcId,identity:{name:'Memory extractor'}},context:{mode:'memory_extraction'},history:[],input:prompt,allowedTools:[]};const work=async()=>{const result=await completeWithFallback(this.primary,this.fallback,extractionTurn,{retries:2,timeoutMs:8000});if(this.blockedServers.has(turn.serverId))return result;const parsed=validate(jsonObject(result.text));for(const memory of parsed.memories.filter(x=>x.importance>=policy(turn).minimum)){if(this.blockedServers.has(turn.serverId))return result;await this.store.remember({serverId:turn.serverId,npcId,characterId,text:memory.text,importance:memory.importance,expiresAt:expiry(memory.retention,turn),memoryKey:memory.key,kind:memory.kind,subject:memory.subject,confidence:memory.confidence,tags:memory.tags,unresolved:memory.unresolved});}if(this.blockedServers.has(turn.serverId))return result;if(parsed.relationship&&Object.keys(parsed.relationship).length)await this.store.adjustRelationshipDimensions(turn.serverId,npcId,characterId,parsed.relationship,parsed.relationshipTag);if(this.blockedServers.has(turn.serverId))return result;if(parsed.playerIntroducedName&&npcId.startsWith('resident:'))await this.residents.noteMeeting(turn.serverId,npcId,characterId,true);return result;};if(this.execute)await this.execute(extractionTurn,work);else await work();}
}

export async function captureDeterministicMemory(store:MemoryStore,turn:TurnInput,response:string){if(!policy(turn).enabled)return;const characterId=String((turn.context.player as any)?.characterId??'unknown-character'),npcId=String(turn.npc.id??'unknown-npc');const remember=async(key:string,text:string,importance:number,kind:string,days?:number,unresolved=false,subject='player')=>importance<policy(turn).minimum?Promise.resolve(undefined):store.remember({serverId:turn.serverId,npcId,characterId,text,importance,memoryKey:key,kind,subject,confidence:1,tags:[kind],unresolved,expiresAt:expiry(days===365?'important':days===30?'routine':'permanent',turn)});const name=turn.input.match(/\b(?:my name is|call me)\s+([a-z][a-z '-]{1,40})\b/i);if(name)await remember('player:name',`The player's introduced name is ${name[1].trim()}.`,1,'introduction');const explicit=turn.input.match(/\bremember(?: that)?\s+(.{3,180})/i);if(explicit)await remember(`explicit:${cleanKey(explicit[1]).slice(0,80)}`,explicit[1].trim(),.9,'core_fact');const promise=turn.input.match(/\b(i promise|you promised|we agreed)\b.{0,160}/i);if(promise)await remember(`promise:${cleanKey(promise[0]).slice(0,80)}`,promise[0].trim(),.9,'promise',undefined,true,'shared');const boundary=turn.input.match(/\b(?:do not|don't|never)\s+(.{3,120})/i);if(boundary)await remember(`boundary:${cleanKey(boundary[1]).slice(0,80)}`,`The player set a boundary: ${boundary[0].trim()}`,.9,'boundary');if(turn.toolResult){const result=JSON.stringify(turn.toolResult).slice(0,500);await remember(`tool:${cleanKey(turn.toolResult.name)}:${cleanKey(result).slice(0,50)}`,`Authoritative shared event: ${result}`,1,'shared_event',365,false,'shared');}if(/\b(kill you|hurt you|threat)\b/i.test(turn.input)){await remember(`threat:${Date.now()}`,`The player threatened the resident: ${turn.input.slice(0,180)}`,1,'grievance',365,true,'shared');await store.adjustRelationshipDimensions(turn.serverId,npcId,characterId,{familiarity:1,trust:-4,warmth:-3,fear:4,irritation:4},'hostile');}else if(/\b(thank you|thanks|you helped)\b/i.test(turn.input))await store.adjustRelationshipDimensions(turn.serverId,npcId,characterId,{familiarity:1,trust:2,warmth:3,obligation:1},'helpful');if(response&&turn.history.length>=4&&(turn.history.length+2)%6===0)await remember(`summary:${Date.now()}`,`Conversation summary: ${[...turn.history.slice(-4),{role:'user',content:turn.input},{role:'assistant',content:response}].map(x=>`${x.role}: ${x.content.replace(/\s+/g,' ').slice(0,180)}`).join(' | ').slice(0,1000)}`,.65,'conversation',30);}
