import { Pool, types } from 'pg';
import { initializePostgresSchema } from '../postgres-schema.js';
import type { MemoryStore,MemoryRecord,RelationshipRecord,RelationshipDimensions } from './store.js';

export class PostgresMemoryStore implements MemoryStore {
  private readonly pool:Pool;constructor(connectionString:string){this.pool=new Pool({connectionString,max:10,types:{getTypeParser:(oid:number,format?:'text'|'binary')=>oid===1184?(value:string)=>new Date(value).toISOString():types.getTypeParser(oid,format)}});}
  async close(){await this.pool.end();}
  async initialize(){await initializePostgresSchema(this.pool, `
    CREATE EXTENSION IF NOT EXISTS pgcrypto;
    CREATE TABLE IF NOT EXISTS ai_npc_memories(id uuid PRIMARY KEY,server_id text NOT NULL,npc_id text NOT NULL,character_id text NOT NULL,text text NOT NULL,importance real NOT NULL,created_at timestamptz NOT NULL,expires_at timestamptz NULL);
    CREATE INDEX IF NOT EXISTS ai_npc_memories_lookup ON ai_npc_memories(server_id,npc_id,character_id,importance DESC);
    CREATE TABLE IF NOT EXISTS ai_npc_relationships(server_id text NOT NULL,npc_id text NOT NULL,character_id text NOT NULL,score real NOT NULL DEFAULT 0,tags jsonb NOT NULL DEFAULT '[]'::jsonb,updated_at timestamptz NOT NULL,PRIMARY KEY(server_id,npc_id,character_id));
    ALTER TABLE ai_npc_memories ADD COLUMN IF NOT EXISTS memory_key text;
    ALTER TABLE ai_npc_memories ADD COLUMN IF NOT EXISTS kind text NOT NULL DEFAULT 'conversation';
    ALTER TABLE ai_npc_memories ADD COLUMN IF NOT EXISTS subject text NOT NULL DEFAULT 'player';
    ALTER TABLE ai_npc_memories ADD COLUMN IF NOT EXISTS confidence real NOT NULL DEFAULT 1;
    ALTER TABLE ai_npc_memories ADD COLUMN IF NOT EXISTS tags jsonb NOT NULL DEFAULT '[]'::jsonb;
    ALTER TABLE ai_npc_memories ADD COLUMN IF NOT EXISTS unresolved boolean NOT NULL DEFAULT false;
    CREATE INDEX IF NOT EXISTS ai_npc_memories_expiry ON ai_npc_memories(expires_at) WHERE expires_at IS NOT NULL;
    CREATE UNIQUE INDEX IF NOT EXISTS ai_npc_memories_key ON ai_npc_memories(server_id,npc_id,character_id,memory_key) WHERE memory_key IS NOT NULL;
    ALTER TABLE ai_npc_relationships ADD COLUMN IF NOT EXISTS familiarity real NOT NULL DEFAULT 0;
    ALTER TABLE ai_npc_relationships ADD COLUMN IF NOT EXISTS trust real NOT NULL DEFAULT 0;
    ALTER TABLE ai_npc_relationships ADD COLUMN IF NOT EXISTS warmth real NOT NULL DEFAULT 0;
    ALTER TABLE ai_npc_relationships ADD COLUMN IF NOT EXISTS respect real NOT NULL DEFAULT 0;
    ALTER TABLE ai_npc_relationships ADD COLUMN IF NOT EXISTS fear real NOT NULL DEFAULT 0;
    ALTER TABLE ai_npc_relationships ADD COLUMN IF NOT EXISTS irritation real NOT NULL DEFAULT 0;
    ALTER TABLE ai_npc_relationships ADD COLUMN IF NOT EXISTS obligation real NOT NULL DEFAULT 0;
    UPDATE ai_npc_relationships SET score=GREATEST(-100,LEAST(100,FLOOR((trust+warmth+respect-fear-irritation+obligation*.5)/4+.5))) WHERE score IS DISTINCT FROM GREATEST(-100,LEAST(100,FLOOR((trust+warmth+respect-fear-irritation+obligation*.5)/4+.5)));`);}
  async purgeExpired(){const result=await this.pool.query('DELETE FROM ai_npc_memories WHERE expires_at IS NOT NULL AND expires_at<=NOW()');return result.rowCount??0;}
  async recall(serverId:string,npcId:string,characterId:string){const r=await this.pool.query<MemoryRecord>(`SELECT id,server_id AS "serverId",npc_id AS "npcId",character_id AS "characterId",text,importance,memory_key AS "memoryKey",kind,subject,confidence,tags,unresolved,created_at AS "createdAt",expires_at AS "expiresAt" FROM ai_npc_memories WHERE server_id=$1 AND npc_id=$2 AND character_id=$3 AND(expires_at IS NULL OR expires_at>NOW()) ORDER BY unresolved DESC,importance DESC,created_at DESC LIMIT 64`,[serverId,npcId,characterId]);return r.rows;}
  async remember(x:Omit<MemoryRecord,'id'|'createdAt'>){const r=await this.pool.query<MemoryRecord>(`INSERT INTO ai_npc_memories(id,server_id,npc_id,character_id,text,importance,created_at,expires_at,memory_key,kind,subject,confidence,tags,unresolved) VALUES(gen_random_uuid(),$1,$2,$3,$4,$5,NOW(),$6,$7,$8,$9,$10,$11,$12) ON CONFLICT(server_id,npc_id,character_id,memory_key) WHERE memory_key IS NOT NULL DO UPDATE SET text=EXCLUDED.text,importance=EXCLUDED.importance,expires_at=EXCLUDED.expires_at,kind=EXCLUDED.kind,subject=EXCLUDED.subject,confidence=EXCLUDED.confidence,tags=EXCLUDED.tags,unresolved=EXCLUDED.unresolved,created_at=NOW() RETURNING id,server_id AS "serverId",npc_id AS "npcId",character_id AS "characterId",text,importance,memory_key AS "memoryKey",kind,subject,confidence,tags,unresolved,created_at AS "createdAt",expires_at AS "expiresAt"`,[x.serverId,x.npcId,x.characterId,x.text,x.importance,x.expiresAt??null,x.memoryKey??null,x.kind??'conversation',x.subject??'player',x.confidence??1,JSON.stringify(x.tags??[]),x.unresolved??false]);return r.rows[0];}
  async forget(serverId:string,npcId:string,characterId:string){const c=await this.pool.connect();try{await c.query('BEGIN');const m=await c.query(`DELETE FROM ai_npc_memories WHERE server_id=$1 AND npc_id=$2 AND character_id=$3`,[serverId,npcId,characterId]);const r=await c.query(`DELETE FROM ai_npc_relationships WHERE server_id=$1 AND npc_id=$2 AND character_id=$3`,[serverId,npcId,characterId]);await c.query('COMMIT');return(m.rowCount??0)+(r.rowCount??0);}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
  async forgetServer(serverId:string){const c=await this.pool.connect();try{await c.query('BEGIN');const m=await c.query(`DELETE FROM ai_npc_memories WHERE server_id=$1`,[serverId]);const r=await c.query(`DELETE FROM ai_npc_relationships WHERE server_id=$1`,[serverId]);await c.query('COMMIT');return(m.rowCount??0)+(r.rowCount??0);}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
  async relationship(serverId:string,npcId:string,characterId:string){const r=await this.pool.query<RelationshipRecord>(`SELECT server_id AS "serverId",npc_id AS "npcId",character_id AS "characterId",score,tags,familiarity,trust,warmth,respect,fear,irritation,obligation,updated_at AS "updatedAt" FROM ai_npc_relationships WHERE server_id=$1 AND npc_id=$2 AND character_id=$3`,[serverId,npcId,characterId]);return r.rows[0]??{serverId,npcId,characterId,score:0,tags:[],familiarity:0,trust:0,warmth:0,respect:0,fear:0,irritation:0,obligation:0,updatedAt:new Date().toISOString()};}
  async adjustRelationship(serverId:string,npcId:string,characterId:string,delta:number,tag?:string){return this.adjustRelationshipDimensions(serverId,npcId,characterId,delta>=0?{warmth:delta,trust:delta,respect:delta,obligation:delta*2}:{warmth:delta,trust:delta,respect:delta,irritation:-delta},tag);}
  async adjustRelationshipDimensions(serverId:string,npcId:string,characterId:string,deltas:Partial<RelationshipDimensions>,tag?:string){const d=(k:keyof RelationshipDimensions)=>Math.max(-10,Math.min(10,(Number.isFinite(deltas[k])?Number(deltas[k]):0)));const r=await this.pool.query<RelationshipRecord>(`
    INSERT INTO ai_npc_relationships(server_id,npc_id,character_id,score,tags,updated_at,familiarity,trust,warmth,respect,fear,irritation,obligation)
    VALUES($1,$2,$3,GREATEST(-100,LEAST(100,FLOOR(($6::real+$7::real+$8::real-$9::real-$10::real+$11::real*.5)/4+.5))),CASE WHEN $4::text IS NULL THEN'[]'::jsonb ELSE jsonb_build_array($4::text)END,NOW(),$5,$6,$7,$8,$9,$10,$11)
    ON CONFLICT(server_id,npc_id,character_id)DO UPDATE SET familiarity=GREATEST(-100,LEAST(100,ai_npc_relationships.familiarity+EXCLUDED.familiarity)),trust=GREATEST(-100,LEAST(100,ai_npc_relationships.trust+EXCLUDED.trust)),warmth=GREATEST(-100,LEAST(100,ai_npc_relationships.warmth+EXCLUDED.warmth)),respect=GREATEST(-100,LEAST(100,ai_npc_relationships.respect+EXCLUDED.respect)),fear=GREATEST(-100,LEAST(100,ai_npc_relationships.fear+EXCLUDED.fear)),irritation=GREATEST(-100,LEAST(100,ai_npc_relationships.irritation+EXCLUDED.irritation)),obligation=GREATEST(-100,LEAST(100,ai_npc_relationships.obligation+EXCLUDED.obligation)),score=GREATEST(-100,LEAST(100,FLOOR((GREATEST(-100,LEAST(100,ai_npc_relationships.trust+EXCLUDED.trust))+GREATEST(-100,LEAST(100,ai_npc_relationships.warmth+EXCLUDED.warmth))+GREATEST(-100,LEAST(100,ai_npc_relationships.respect+EXCLUDED.respect))-GREATEST(-100,LEAST(100,ai_npc_relationships.fear+EXCLUDED.fear))-GREATEST(-100,LEAST(100,ai_npc_relationships.irritation+EXCLUDED.irritation))+GREATEST(-100,LEAST(100,ai_npc_relationships.obligation+EXCLUDED.obligation))*.5)/4+.5))),tags=CASE WHEN $4::text IS NULL OR ai_npc_relationships.tags?$4::text THEN ai_npc_relationships.tags ELSE (SELECT jsonb_agg(value ORDER BY ord) FROM jsonb_array_elements(ai_npc_relationships.tags||jsonb_build_array($4::text)) WITH ORDINALITY AS t(value,ord) WHERE ord>GREATEST(0,jsonb_array_length(ai_npc_relationships.tags)+1-12))END,updated_at=NOW()
    RETURNING server_id AS "serverId",npc_id AS "npcId",character_id AS "characterId",score,tags,familiarity,trust,warmth,respect,fear,irritation,obligation,updated_at AS "updatedAt"`,[serverId,npcId,characterId,tag??null,d('familiarity'),d('trust'),d('warmth'),d('respect'),d('fear'),d('irritation'),d('obligation')]);return r.rows[0];}
}
